### ISSUE TITLE
Localhost problem

### ISSUE THREAD

**Issue by mikkeschiren** [boyney123/garie#2]
I get this on localhost::

`Error: No default engine was specified and no extension was provided.
    at new View (/usr/src/app/node_modules/express/lib/view.js:61:11)
    at Function.render (/usr/src/app/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
    at /usr/src/app/app.js:40:7
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:315:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/app.js:29:3
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/usr/src/app/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:109:7)`

It's something missing?

**Comment by CharlyWebsterJG** [comment]
same question :D

**Comment by CharlyWebsterJG** [comment]
It was 'res.render('error')' causing this issue in app.js

**Comment by boyney123** [comment]
Hi @CharlyWebsterJG and @mikkeschiren 

Thanks for raising the issue.

I'l take a look, looks like something I missed.

I'm currently moving over to Garie v2 at the moment, so it might be fixed soon!

**Comment by boyney123** [comment]
Garie 2.0 is released, this should no longer be an issue

**Comment by CharlyWebsterJG** [comment]
Looks great but unfortunately recreated to fit my need when it wasn’t working.
