### ISSUE TITLE
Failing fresh install docker-compose

### ISSUE THREAD

**Issue by danipolo** [boyney123/garie#29]
I'm trying to launch it following documentation and it's failing. This docker output:

```
➜  garie (master) ✗ ./start.sh 
Starting garie_influxdb_1 ... done
Starting garie_grafana_1                  ... done
Starting garie_chronograf_1               ... done
Starting garie_garie-pagespeed-insights_1 ... done
Starting garie_garie-lighthouse_1         ... done
Starting garie_garie-browsertime_1        ... done
Attaching to garie_influxdb_1, garie_chronograf_1, garie_garie-pagespeed-insights_1, garie_garie-browsertime_1, garie_grafana_1, garie_garie-lighthouse_1
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Starting Grafana" logger=server version=6.5.1 commit=1763a0f branch=HEAD compiled=2019-11-28T07:43:49+0000
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="App mode production" logger=settings
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Initializing SqlStore" logger=server
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Starting DB migration" logger=migrator
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Initializing HTTPServer" logger=server
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Initializing OSSLicensingService" logger=server
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Initializing SearchService" logger=server
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Initializing RemoteCache" logger=server
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Initializing QuotaService" logger=server
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Initializing ServerLockService" logger=server
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Initializing UserAuthTokenService" logger=server
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Initializing PluginManager" logger=server
grafana_1                   | t=2019-12-04T20:50:55+0000 lvl=info msg="Starting plugin search" logger=plugins
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing RenderingService" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing AlertEngine" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing DatasourceCacheService" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing HooksService" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing LoginService" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing InternalMetricsService" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing TracingService" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing UsageStatsService" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing CleanUpService" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing NotificationService" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing provisioningServiceImpl" logger=server
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="deleted datasource based on configuration" logger=provisioning.datasources name=Lighthouse
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="inserting datasource from configuration " logger=provisioning.datasources name=Lighthouse
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Backend rendering via phantomJS" logger=rendering
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin." logger=rendering
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="Initializing Stream Manager"
grafana_1                   | t=2019-12-04T20:50:56+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
garie-pagespeed-insights_1  | 
garie-pagespeed-insights_1  | > garie-pagespeed-insights@0.0.1 start /usr/src/garie-pagespeed-insights
garie-pagespeed-insights_1  | > node ./src/index.js
garie-pagespeed-insights_1  | 
garie-browsertime_1         | 
garie-browsertime_1         | > garie-browertime@0.0.1 start /usr/src/garie-browsertime
garie-browsertime_1         | > node ./src/index.js
garie-browsertime_1         | 
garie-lighthouse_1          | 
garie-lighthouse_1          | > garie-lighthouse@0.0.1 start /usr/src/garie-lighthouse
garie-lighthouse_1          | > node ./src/index.js
garie-lighthouse_1          | 
garie-browsertime_1         | Application listening on port 3000
garie-browsertime_1         | { Error: connect ECONNREFUSED 172.24.0.2:8086
garie-browsertime_1         |     at Object._errnoException (util.js:1022:11)
garie-browsertime_1         |     at _exceptionWithHostPort (util.js:1044:20)
garie-browsertime_1         |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
garie-browsertime_1         |   code: 'ECONNREFUSED',
garie-browsertime_1         |   errno: 'ECONNREFUSED',
garie-browsertime_1         |   syscall: 'connect',
garie-browsertime_1         |   address: '172.24.0.2',
garie-browsertime_1         |   port: 8086 }
garie-browsertime_1         | (node:16) UnhandledPromiseRejectionWarning: Failed to initialise influx
garie-browsertime_1         | (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
garie-browsertime_1         | (node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
chronograf_1                | time="2019-12-04T20:50:59Z" level=info msg="Serving chronograf at http://[::]:8888" component=server 
chronograf_1                | time="2019-12-04T20:50:59Z" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime" 
garie-pagespeed-insights_1  | Application listening on port 3000
garie-pagespeed-insights_1  | { Error: connect ECONNREFUSED 172.24.0.2:8086
garie-pagespeed-insights_1  |     at Object._errnoException (util.js:1022:11)
garie-pagespeed-insights_1  |     at _exceptionWithHostPort (util.js:1044:20)
garie-pagespeed-insights_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
garie-pagespeed-insights_1  |   code: 'ECONNREFUSED',
garie-pagespeed-insights_1  |   errno: 'ECONNREFUSED',
garie-pagespeed-insights_1  |   syscall: 'connect',
garie-pagespeed-insights_1  |   address: '172.24.0.2',
garie-pagespeed-insights_1  |   port: 8086 }
garie-pagespeed-insights_1  | (node:16) UnhandledPromiseRejectionWarning: Failed to initialise influx
garie-pagespeed-insights_1  | (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
garie-pagespeed-insights_1  | (node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm not sure why is happening because in docker-compose it "depends" on influx. Any ideas?

**Comment by jonwest** [comment]
Same behaviour here.

**Comment by jonwest** [comment]
Likely caused by the fact that this repo hasn't been updated in over a year, but if I changed by InfluxDB version to `1.6.6` rather than `latest`, given that 1.6 was "latest" in October of last year, it works.

**Comment by lahaxearnaud** [comment]
I made a pull request for this issue #30

**Comment by boyney123** [comment]
Yeah sorry, guys, I don't really maintain this project at the moment, but I have merged the PR #30 hopefully that fixes this issue?
